### ISSUE TITLE
Server disconnected from iOS

### ISSUE THREAD

**Issue by jocull** [jribble/Java-Websockify#1]
There is something going on where iOS clients (maybe Android as well - have not been able to test) are not able to connect. Somewhere early in the connection process it simply disconnects. I'll be digging into this but wanted to see if you had ideas on what was wrong with it?

**Comment by jocull** [comment]
This also happens in desktop Safari and this may be related? https://github.com/kanaka/noVNC/issues/143

**Comment by jribble** [comment]
I'm sorry I haven't tried using any mobile clients with Java-Websockify, so I don't have any insight.  I will try to take a look at this on desktop Safari soon.

**Comment by jocull** [comment]
So... I am digging into this, specifically around draft spec 76. Am I correct in my understanding that the code here doesn't use any of the draft specs include in the repo? They seem to be in there but just sort of dangling and not used by anything. Can you shed some light on this? My plan was to upgrade them to the latest versions ( https://github.com/TooTallNate/Java-WebSocket ) and see what progress that made if any.

**Comment by jocull** [comment]
Wow, I am sorry that is totally inaccurate. I must have merged projects on accident - there are no draft specs in this project. My apologies.

**Comment by jocull** [comment]
I've figured this out and created a patch. I will create a pull request with the details.
